# Generated by Django 4.2.28 on 2026-02-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("ical_feed_url", models.URLField(blank=True, max_length=500)),
                ("last_polled", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("datetime", models.DateTimeField()),
                (
                    "artists",
                    models.TextField(
                        help_text="List of performing artists/bands, one per line"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source of the event (e.g., 'user submission', 'venue feed')",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the event"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Link to event details / tickets",
                        max_length=500,
                    ),
                ),
                (
                    "submitter_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of submitter (for rate limiting)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genre_tags",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.genre"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["datetime"],
                "indexes": [
                    models.Index(
                        fields=["datetime"], name="events_even_datetim_3a55f7_idx"
                    ),
                    models.Index(
                        fields=["status", "datetime"],
                        name="events_even_status_73a115_idx",
                    ),
                ],
            },
        ),
    ]
